name: IRIS Deployment
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          with:
            node-version: '20'
      
      - name: install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'
      
      - name: install AWS CDK
        run: 'sudo npm install -g aws-cdk'
      
      - name: install dependencies
        run: 'sudo npm install'
      
      - name: CDK Synth
        run: 'cdk synth'
  
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
        
      - name: Configure Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'
      
      - name: cdk deploy
        run: cdk deploy
        
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
        
      - name: Configure Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'
      
      - name: cdk deploy
        run: cdk deploy