name: IRIS Deployment
on: 
  push:
    branches: [ main ]
    workflow_dispatch:
    
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # - name: cdk diff
      #   uses: youyo/aws-cdk-github-actions@v2
      #   with:
      #     cdk_subcommand: 'diff'
      #     actions_comment: true
      - name: Configure Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'
      
      - name: install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'
      
      - name: install AWS CDK
        run: 'sudo npm install -g aws-cdk'
      
      - name: install dependencies
        run: 'sudo npm install'
      
      - name: CDK Synth
        run: 'cdk synth'
        working-directory: GitActionIRISDeploy
      
      - name: cdk deploy
        run: cdk deploy
        working-directory: GitActionIRISDeploy
        
